#create itom-node-manager service account
apiVersion: v1
kind: ServiceAccount
metadata:
  name: itom-node-manager
  namespace: {CDF_NAMESPACE}

#create clusterrole for itom-node-manager
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: microfocus:cdf:itom-node-manager
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - delete
  - get
  - patch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - delete
  - list
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - delete
  - get
  - list
- apiGroups:
  - apps
  resources:
  - daemonsets
  verbs:
  - patch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - list


---
#create cluster rolebinding for itom-node-manager
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: microfocus:cdf:itom-node-manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: microfocus:cdf:itom-node-manager
subjects:
- kind: ServiceAccount
  name: itom-node-manager
  namespace: {CDF_NAMESPACE}
